Areas/Admin/Controllers/CouponController.cs
using FoodChill.Data;
using FoodChill.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace FoodChill.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CouponController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CouponController(ApplicationDbContext db)
        {
            _db = db;
        }

        //GET -- Index
        public async Task<IActionResult> Index()
        {
            var model = await _db.Coupon.ToListAsync();
            return View(model);
        }

        //GET -- Create
        public IActionResult Create()
        {
            return View();
        }

        //POST -- Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Coupon coupons)
        {
            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0)
                {
                    byte[] cpnPictur = null;
                    using (var fileStream = files[0].OpenReadStream())
                    {
                        using (var memoryStream = new MemoryStream())
                        {
                            fileStream.CopyTo(memoryStream);
                            cpnPictur = memoryStream.ToArray();
                        }
                    }
                    coupons.Picture = cpnPictur;
                }
                _db.Coupon.Add(coupons);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(coupons);
        }

        //GET -- Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var CouponItem = await _db.Coupon.SingleOrDefaultAsync(m => m.ID == id);
            if (CouponItem == null)
            {
                return NotFound();
            }
            return View(CouponItem);
        }

        //POST -- Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Coupon coupons)
        {
            if (coupons.ID == 0)
            {
                return NotFound();
            }

            var couponFromDb = await _db.Coupon.Where(c => c.ID == coupons.ID).FirstOrDefaultAsync();

            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0)
                {
                    byte[] cpnPictur = null;
                    using (var fileStream = files[0].OpenReadStream())
                    {
                        using (var memoryStream = new MemoryStream())
                        {
                            fileStream.CopyTo(memoryStream);
                            cpnPictur = memoryStream.ToArray();
                        }
                    }
                    couponFromDb.Picture = cpnPictur;
                }

                couponFromDb.Name = coupons.Name;
                couponFromDb.MinimumAmount = coupons.MinimumAmount;
                couponFromDb.Discount = coupons.Discount;
                couponFromDb.CouponType = coupons.CouponType;
                couponFromDb.IsActive = coupons.IsActive;

                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(coupons);
        }

        //GET -- Details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var Coupon = await _db.Coupon.SingleOrDefaultAsync(m => m.ID == id);
            if (Coupon == null)
            {
                return NotFound();
            }
            return View(Coupon);
        }

        //GET -- Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var coupon = await _db.Coupon.SingleOrDefaultAsync(c => c.ID == id);
            if (coupon == null)
            {
                return NotFound();
            }
            return View(coupon);
        }

        //POST -- Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var coupon = await _db.Coupon.SingleOrDefaultAsync(c => c.ID == id);
            _db.Coupon.Remove(coupon);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));

        }
    }
}

Areas/Admin/Controllers/UserController.cs
using FoodChill.Data;
using FoodChill.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace FoodChill.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.ManagerUser)]
    [Area("Admin")]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _db;

        public UserController(ApplicationDbContext db)
        {
            _db = db;
        }



        public async Task<IActionResult> Index()
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            return View(await _db.ApplicationUser.Where(c => c.Id != claim.Value).ToListAsync());
        }

        public async Task<IActionResult> Lock(string id)
        {
            if (id==null)
            {
                return NotFound();
            }
            var applicationUser = await _db.ApplicationUser.FirstOrDefaultAsync(l => l.Id == id);
            if (applicationUser == null)
            {
                return NotFound();
            }
            applicationUser.LockoutEnd = DateTime.Now.AddHours(2);
            
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> UnLock(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var applicationUser = await _db.ApplicationUser.FirstOrDefaultAsync(l => l.Id == id);
            if (applicationUser == null)
            {
                return NotFound();
            }
            applicationUser.LockoutEnd = DateTime.Now;

            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Shared/CreateAndBackToIndex.cshtml
<div class="form-row">
    <div class="col-5 ">
        <input type="submit" class="btn btn-success form-control" value="Create" />
    </div>
    <div class="col-5">
        <a asp-action="Index" class="btn btn-primary form-control">Back to Index </a>
    </div>
</div>

Views/Shared/TableButtonPartial.cshtml
@model int
<td style="width:150px">
    <div class="btn-group" role="group">
        <a class="btn btn-primary text-dark " asp-action="Edit" asp-route-ID="@Model"><i class="fas fa-edit"></i></a>
        <a class="btn btn-primary text-dark" asp-action="Details" asp-route-ID="@Model"><i class="fas fa-info-circle"></i></a>
        <a class="btn btn-primary text-dark" asp-action="Delete" asp-route-ID="@Model"><i class="fas fa-trash-alt"></i></a>
    </div>
</td>

Views/Shared/_CreateButtonPartial.cshtml
<p>
    <a asp-action="Create" class="btn btn-info"><i class="fas fa-plus-square"></i> &nbsp; Create New</a>

</p>

Views/Shared/_DeleteAndBackToListPartial.cshtml
@model int

<div class="row">
    <div class="col-5 ">
        <input type="submit" class="btn btn-danger form-control" value="Delete" asp-route-id="@Model" />
    </div>
    <div class="col-5">
        <a asp-action="Index" class="btn btn-primary form-control">Back to List </a>
    </div>
</div>

Views/Shared/_DetailsAndBackToListPartial.cshtml
@model int

<div class="row">
    <div class="col-5 ">
        <a asp-action="Edit" class="btn btn-success form-control" asp-route-id="@Model">Edit</a>
    </div>
    <div class="col-5">
        <a asp-action="Index" class="btn btn-primary form-control">Back to List </a>
    </div>
</div>

Views/Shared/_EditAndBackToListPartial.cshtml
@model int
    <div class="row">
        <div class="col-5 ">
            <input type="submit" class="btn btn-success form-control" value="Update" asp-route-id="@Model" />
        </div>
        <div class="col-5">
            <a asp-action="Index" class="btn btn-primary form-control">Back to List </a>
        </div>
    </div>

Views/Shared/_IndividualOrderDetails.cshtml
@model FoodChill.Models.ViewModels.OrderDetailsViewModel
@using FoodChill.Utility
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<form asp-action="OrderPickup" asp-controller="Order" asp-route-orderId="@Model.OrderHeader.ID" method="post">
    <div class="container row border ml-1 backgroundWhiteBorder10Padding" style="width:100%">
        <div class="col-lg-8 col-12" style="border-right:1px solid #bbb9b9">
            <br />
            <input type="hidden" asp-for="OrderHeader.ID" />

            <div class="form-group row">
                <div class="col-3">
                    <label>Name</label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.PickupName" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label asp-for="OrderHeader.ApplicationUser.Email"></label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.ApplicationUser.Email" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label asp-for="OrderHeader.ApplicationUser.PhoneNumber"></label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.ApplicationUser.PhoneNumber" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label asp-for="OrderHeader.OrderTotal"></label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.OrderTotal" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label asp-for="OrderHeader.OrderDate"></label>
                </div>
                <div class="col-9">
                    <input value="@Model.OrderHeader.PickUpTime.ToShortDateString() @Model.OrderHeader.PickUpTime.ToShortTimeString()" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label asp-for="OrderHeader.Comments"></label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.Comments" disabled class="form-control" />
                </div>
            </div>
        </div>

        <div class="col-lg-4 col-12">
            <h4 class="d-flex justify-content-between align-content-center mb-3">
                <span class="text-muted">Order ID: </span>
                <span class="badge badge-secondary badge-pill">@Model.OrderHeader.ID</span>
            </h4>
            <ul class="list-group mb-3">
                @foreach (var details in Model.OrderDetails)
                {
                    <li class="list-group-item d-flex justify-content-between">
                        <div>
                            <h6 class="my-0">@details.Name</h6>
                            <small class="text-muted">Quantity : @details.Count</small>
                        </div>
                        <span class="text-muted">@(details.Price * details.Count)</span>
                    </li>
                }
                @if (Model.OrderHeader.CouponCode != null)
                {
                    <li class="list-group-item d-flex justify-content-between">
                        <div class="text-success">
                            <h6 class="my-0">Promo Code</h6>
                            <small>@Model.OrderHeader.CouponCode</small>
                        </div>
                        <span class="text-success">@(Model.OrderHeader.OrderTotalOriginal-Model.OrderHeader.OrderTotal)</span>
                    </li>
                }
                <li class="list-group-item d-flex justify-content-between bg-light">
                    <span class="text-info"> Total (USD)</span>
                    <strong class="text-info">$@Model.OrderHeader.OrderTotal</strong>
                </li>

            </ul>

            @if (Model.OrderHeader.Status.Equals(SD.StatusReady) && (User.IsInRole(SD.ManagerUser) || User.IsInRole(SD.FrontDeskUser)))
            {
                <button type="submit" class="btn btn-success form-control"><i class="far fa-thumbs-up"></i> Confirm Pickup</button>
            }
            else
            {
                <button type="submit" disabled class="btn btn-info form-control">@Model.OrderHeader.Status</button>
            }

        </div>

    </div>
</form>

Views/Shared/_Layout.cshtml
@using FoodChill.Utility
@using Microsoft.AspNetCore.Http

@inject IHttpContextAccessor  HttpContextAccessor
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FoodChill</title>
    <script src="https://kit.fontawesome.com/d4a083258e.js" crossorigin="anonymous"></script>
    <script src="https://cdn.tiny.cloud/1/iqn15aqi4hdu2s83dlgten4u0i4grvjdaqfcaa1vsy64qkb1/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="~/js/jquery-ui.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/jquery-ui.css" />
   

</head>

<body class="search-background">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <img src="~/images/mild.png" />
                <img src="~/images/spicy.png" />
                <img src="~/images/verySpicy.png" />
                <a class="navbar-brand text-info" style="cursor:pointer" asp-area="" asp-controller="Home" asp-action="Index">FoodChill</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @*<li><partial name="~/Views/Shared/_CreateButtonPartial.cshtml" /></li>
        <li><partial name="~/Views/Shared/_CreateButtonPartial" /></li>*@
                        @*<li><partial name="_CreateButtonPartial" /></li>*@
                        @if (User.IsInRole(SD.ManagerUser))
                        {
                            <li class="nav-item dropdown text-white-50">
                                <a class="nav-link dropdown-toggle" href="#" id="dropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Content Management
                                </a>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="SubCategory" asp-action="Index">Sub Category</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="MenuItem" asp-action="Index">Menu Item</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Coupon" asp-action="Index">Coupons</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">Users</a>
                                </div>
                            </li>
                        }
                        @if (User.IsInRole(SD.ManagerUser) || User.IsInRole(SD.CustomerEndUser) || User.IsInRole(SD.FrontDeskUser) || User.IsInRole(SD.KitchenUser))
                        {
                            <li class="nav-item">
                                <a asp-area="Customer" asp-controller="Order" asp-action="OrderHistory" class="nav-link">
                                    Order History
                                </a>
                            </li>
                        }

                        @if (User.IsInRole(SD.FrontDeskUser) || User.IsInRole(SD.KitchenUser) || User.IsInRole(SD.ManagerUser))
                        {
                            <li class="nav-item dropdown text-white-50">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Order
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropDownMenuLink">
                                    @if (User.IsInRole(SD.KitchenUser) || User.IsInRole(SD.ManagerUser))
                                    {
                                        <a class="dropdown-item" asp-action="ManageOrder" asp-controller="Order" asp-area="Customer">Manage Order</a>
                                    }
                                    @if (User.IsInRole(SD.FrontDeskUser) || User.IsInRole(SD.ManagerUser))
                                    {
                                        <a class="dropdown-item" asp-action="OrderPickup" asp-controller="Order" asp-area="Customer">Order Pickup</a>
                                    }
                                </div>
                            </li>
                        }

                        @if (HttpContextAccessor.HttpContext.Session.GetInt32(@SD.ssShoppingCartCount) != null)
                        {
                            <li style="color:wheat">
                                <a asp-area="Customer" asp-controller="Cart" asp-action="Index" class="nav-link">
                                    &nbsp
                                    @{
                                        var count = HttpContextAccessor.HttpContext.Session.GetInt32(@SD.ssShoppingCartCount);
                                    }
                                    <i class="fas fa-shopping-cart"></i>&nbsp; (@count)
                                </a>
                            </li>
                        }
                        else
                        {
                            <li style="color:wheat">
                                <a href="#" class="nav-link">
                                    <i class="fas fa-shopping-cart"></i>&nbsp; (0)
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top pl-3 footer text-white-50" style="background-color: #343a40;">
        <div class="container">
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.js"></script>

    @RenderSection("Scripts", required: false)
</body>

</html>

Views/Shared/_OrderStatus.cshtml
@model string
@using FoodChill.Utility

<div style="width:100%">
    
    @if (Model == SD.StatusSubmitted)
    {
        <img src="~/images/OrderPlaced.png" width="100%" />
    }
    @if (Model == SD.StatusInProcess)
    {
        <img src="~/images/InKitchen.png" width="100%" />
    }
    @if (Model == SD.StatusReady)
    {
        <img src="~/images/ReadyForPickup.png" width="100%" />
    }
    @if (Model == SD.StatusCompleted)
    {
        <img src="~/images/completed.png" width="100%" />
    }

</div> 

Views/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}

Views/Shared/_ThumbnailCategoryPartial.cshtml
@model IEnumerable<MenuItem>
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@if (Model.Count() > 0)
{
    <div class="col-12 post @Model.FirstOrDefault().Category.Name.Replace(" ", string.Empty) menu-restaurent">
        <div class="row">
            <h3 class="text-success">@Model.FirstOrDefault().Category.Name</h3>
        </div>

        @foreach (var item in Model)
        {
            <div class="border border-info rounded col-12" style="margin-bottom:10px; margin-top:10px; padding: 10px">
                <div class="row">
                    <div class="col-md-3 col-sm-12">
                        <img src="@item.Image"height="220px" width="99%" style="border-radius: 5px; border: 1px solid #bbb9b9 " />
                    </div>
                    <div class="col-md-9 col-sm-12">
                        <div class="row pr-3">
                            <div class="col-8">
                                <label class="text-primary" style="font-size:21px; color:maroon">@item.Name</label>
                                @if (item.Spicyness == "1")
                                {
                                    <img src="~/images/mild.png" title="Mild" />
                                }
                                @if (item.Spicyness == "2")
                                {
                                    <img src="~/images/spicy.png" title="Spicy" />
                                }
                                @if (item.Spicyness == "3")
                                {
                                    <img src="~/images/verySpicy.png" title="Very Spicy" />
                                }
                            </div>
                            <div class="col-4 text-right" style="color:darkred">
                                <h3>$ @item.Price</h3>
                            </div>
                        </div>
                        <div class="row col-12 text-justify d-none d-md-block">
                            <p> @Html.Raw(item.Description)</p>
                        </div>
                        <div class="col-md-3 col-sm-12 offset-md-9 text-center">
                            <a asp-route-id="@item.ID"  asp-action="Details" class="btn btn-primary form-control">Details</a>
                        </div> 

                    </div>
                </div>
            </div>
        }

    </div>
}